#!/bin/bash
date=$(date +%H | sed 's/\<0//g')

if [[ "$date" -le "9" ]]; then
  sh ~/.scripts/wal.sh "$PWD/wallpapers/dynamic_$(($date - 4)).tiff"
elif [[ "$date" -le "16" ]]; then
  sh ~/.scripts/wal.sh "$PWD/wallpapers/dynamic_$(($date - 5)).tiff"
elif [[ "$date" -le "21" ]]; then
  sh ~/.scripts/wal.sh "$PWD/wallpapers/dynamic_$(($date - 6)).tiff"
else
  sh ~/.scripts/wal.sh "$PWD/wallpapers/dynamic_16.tiff"
fi
